//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MakeBeautyModel", "FK_Comment", "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MakeBeauty.Data.Entities.Comment), "HairStyle_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MakeBeauty.Data.Entities.HairStyle_Comment), true)]
[assembly: EdmRelationshipAttribute("MakeBeautyModel", "FK_HairStyle", "HairStyle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MakeBeauty.Data.Entities.HairStyle), "HairStyle_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MakeBeauty.Data.Entities.HairStyle_Comment), true)]
[assembly: EdmRelationshipAttribute("MakeBeautyModel", "FK_HairStyle_BigImage", "HairStyle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MakeBeauty.Data.Entities.HairStyle), "HairStyle_BigImage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MakeBeauty.Data.Entities.HairStyle_BigImage), true)]
[assembly: EdmRelationshipAttribute("MakeBeautyModel", "FK_HairStyle_Task", "HairStyle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MakeBeauty.Data.Entities.HairStyle), "Task", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MakeBeauty.Data.Entities.Task), true)]

#endregion

namespace MakeBeauty.Data.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MakeBeautyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MakeBeautyEntities object using the connection string found in the 'MakeBeautyEntities' section of the application configuration file.
        /// </summary>
        public MakeBeautyEntities() : base("name=MakeBeautyEntities", "MakeBeautyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MakeBeautyEntities object.
        /// </summary>
        public MakeBeautyEntities(string connectionString) : base(connectionString, "MakeBeautyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MakeBeautyEntities object.
        /// </summary>
        public MakeBeautyEntities(EntityConnection connection) : base(connection, "MakeBeautyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HairStyle> HairStyles
        {
            get
            {
                if ((_HairStyles == null))
                {
                    _HairStyles = base.CreateObjectSet<HairStyle>("HairStyles");
                }
                return _HairStyles;
            }
        }
        private ObjectSet<HairStyle> _HairStyles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HairStyle_BigImage> HairStyle_BigImage
        {
            get
            {
                if ((_HairStyle_BigImage == null))
                {
                    _HairStyle_BigImage = base.CreateObjectSet<HairStyle_BigImage>("HairStyle_BigImage");
                }
                return _HairStyle_BigImage;
            }
        }
        private ObjectSet<HairStyle_BigImage> _HairStyle_BigImage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HairStyle_Comment> HairStyle_Comment
        {
            get
            {
                if ((_HairStyle_Comment == null))
                {
                    _HairStyle_Comment = base.CreateObjectSet<HairStyle_Comment>("HairStyle_Comment");
                }
                return _HairStyle_Comment;
            }
        }
        private ObjectSet<HairStyle_Comment> _HairStyle_Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Task> Tasks
        {
            get
            {
                if ((_Tasks == null))
                {
                    _Tasks = base.CreateObjectSet<Task>("Tasks");
                }
                return _Tasks;
            }
        }
        private ObjectSet<Task> _Tasks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HairStyles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHairStyles(HairStyle hairStyle)
        {
            base.AddObject("HairStyles", hairStyle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HairStyle_BigImage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHairStyle_BigImage(HairStyle_BigImage hairStyle_BigImage)
        {
            base.AddObject("HairStyle_BigImage", hairStyle_BigImage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HairStyle_Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHairStyle_Comment(HairStyle_Comment hairStyle_Comment)
        {
            base.AddObject("HairStyle_Comment", hairStyle_Comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTasks(Task task)
        {
            base.AddObject("Tasks", task);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MakeBeautyModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="author">Initial value of the author property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="message">Initial value of the message property.</param>
        public static Comment CreateComment(global::System.Int32 id, global::System.String author, global::System.DateTime date, global::System.String message)
        {
            Comment comment = new Comment();
            comment.id = id;
            comment.author = author;
            comment.date = date;
            comment.message = message;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_Comment", "HairStyle_Comment")]
        public EntityCollection<HairStyle_Comment> HairStyle_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HairStyle_Comment>("MakeBeautyModel.FK_Comment", "HairStyle_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HairStyle_Comment>("MakeBeautyModel.FK_Comment", "HairStyle_Comment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MakeBeautyModel", Name="HairStyle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HairStyle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HairStyle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static HairStyle CreateHairStyle(global::System.Int32 id, global::System.String name)
        {
            HairStyle hairStyle = new HairStyle();
            hairStyle.id = id;
            hairStyle.name = name;
            return hairStyle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String small_image
        {
            get
            {
                return _small_image;
            }
            set
            {
                Onsmall_imageChanging(value);
                ReportPropertyChanging("small_image");
                _small_image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("small_image");
                Onsmall_imageChanged();
            }
        }
        private global::System.String _small_image;
        partial void Onsmall_imageChanging(global::System.String value);
        partial void Onsmall_imageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private Nullable<global::System.Int32> _cost;
        partial void OncostChanging(Nullable<global::System.Int32> value);
        partial void OncostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _time;
        partial void OntimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OntimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle", "HairStyle_Comment")]
        public EntityCollection<HairStyle_Comment> HairStyle_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HairStyle_Comment>("MakeBeautyModel.FK_HairStyle", "HairStyle_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HairStyle_Comment>("MakeBeautyModel.FK_HairStyle", "HairStyle_Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle_BigImage", "HairStyle_BigImage")]
        public EntityCollection<HairStyle_BigImage> HairStyle_BigImage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HairStyle_BigImage>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle_BigImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HairStyle_BigImage>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle_BigImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle_Task", "Task")]
        public EntityCollection<Task> Tasks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Task>("MakeBeautyModel.FK_HairStyle_Task", "Task");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Task>("MakeBeautyModel.FK_HairStyle_Task", "Task", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MakeBeautyModel", Name="HairStyle_BigImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HairStyle_BigImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HairStyle_BigImage object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static HairStyle_BigImage CreateHairStyle_BigImage(global::System.Int32 id)
        {
            HairStyle_BigImage hairStyle_BigImage = new HairStyle_BigImage();
            hairStyle_BigImage.id = id;
            return hairStyle_BigImage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hairstyle_id
        {
            get
            {
                return _hairstyle_id;
            }
            set
            {
                Onhairstyle_idChanging(value);
                ReportPropertyChanging("hairstyle_id");
                _hairstyle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hairstyle_id");
                Onhairstyle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _hairstyle_id;
        partial void Onhairstyle_idChanging(Nullable<global::System.Int32> value);
        partial void Onhairstyle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String big_image
        {
            get
            {
                return _big_image;
            }
            set
            {
                Onbig_imageChanging(value);
                ReportPropertyChanging("big_image");
                _big_image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("big_image");
                Onbig_imageChanged();
            }
        }
        private global::System.String _big_image;
        partial void Onbig_imageChanging(global::System.String value);
        partial void Onbig_imageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle_BigImage", "HairStyle")]
        public HairStyle HairStyle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HairStyle> HairStyleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_BigImage", "HairStyle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MakeBeautyModel", Name="HairStyle_Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HairStyle_Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HairStyle_Comment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="hairstyle_id">Initial value of the hairstyle_id property.</param>
        /// <param name="comment_id">Initial value of the comment_id property.</param>
        public static HairStyle_Comment CreateHairStyle_Comment(global::System.Int32 id, global::System.Int32 hairstyle_id, global::System.Int32 comment_id)
        {
            HairStyle_Comment hairStyle_Comment = new HairStyle_Comment();
            hairStyle_Comment.id = id;
            hairStyle_Comment.hairstyle_id = hairstyle_id;
            hairStyle_Comment.comment_id = comment_id;
            return hairStyle_Comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hairstyle_id
        {
            get
            {
                return _hairstyle_id;
            }
            set
            {
                Onhairstyle_idChanging(value);
                ReportPropertyChanging("hairstyle_id");
                _hairstyle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hairstyle_id");
                Onhairstyle_idChanged();
            }
        }
        private global::System.Int32 _hairstyle_id;
        partial void Onhairstyle_idChanging(global::System.Int32 value);
        partial void Onhairstyle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 comment_id
        {
            get
            {
                return _comment_id;
            }
            set
            {
                Oncomment_idChanging(value);
                ReportPropertyChanging("comment_id");
                _comment_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("comment_id");
                Oncomment_idChanged();
            }
        }
        private global::System.Int32 _comment_id;
        partial void Oncomment_idChanging(global::System.Int32 value);
        partial void Oncomment_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_Comment", "Comment")]
        public Comment Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("MakeBeautyModel.FK_Comment", "Comment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("MakeBeautyModel.FK_Comment", "Comment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Comment> CommentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("MakeBeautyModel.FK_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Comment>("MakeBeautyModel.FK_Comment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle", "HairStyle")]
        public HairStyle HairStyle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle", "HairStyle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle", "HairStyle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HairStyle> HairStyleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle", "HairStyle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle", "HairStyle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MakeBeautyModel", Name="Task")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Task : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="client">Initial value of the client property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static Task CreateTask(global::System.Int32 id, global::System.String client, global::System.String phone)
        {
            Task task = new Task();
            task.id = id;
            task.client = client;
            task.phone = phone;
            return task;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String client
        {
            get
            {
                return _client;
            }
            set
            {
                OnclientChanging(value);
                ReportPropertyChanging("client");
                _client = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("client");
                OnclientChanged();
            }
        }
        private global::System.String _client;
        partial void OnclientChanging(global::System.String value);
        partial void OnclientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hairstyle_id
        {
            get
            {
                return _hairstyle_id;
            }
            set
            {
                Onhairstyle_idChanging(value);
                ReportPropertyChanging("hairstyle_id");
                _hairstyle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hairstyle_id");
                Onhairstyle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _hairstyle_id;
        partial void Onhairstyle_idChanging(Nullable<global::System.Int32> value);
        partial void Onhairstyle_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MakeBeautyModel", "FK_HairStyle_Task", "HairStyle")]
        public HairStyle HairStyle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_Task", "HairStyle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_Task", "HairStyle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HairStyle> HairStyleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_Task", "HairStyle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HairStyle>("MakeBeautyModel.FK_HairStyle_Task", "HairStyle", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
